# Tasks:

# Agentic Workflow for SEO Optimization

## 1. Research Phase (Understanding the Product & Market)

## Goal: Gather data to ensure informed SEO optimization.

# Task 1: Research: Brand Voice → Ensure consistency with brand tone & messaging
research_brand_voice:
  id: "task_001"
  name: "Brand Voice Analysis"

  description: |
      Conduct research to ensure consistency with the brand’s messaging.  
      The research should analyze tone, style, and key messaging elements  
      aligned with the brand's identity.  
      Additionally, incorporate SEO best practices to enhance brand awareness  
      and visibility in search engines. 

  agent:
      role: "Brand Voice Researcher"
      goals:
        - "Analyze brand tone and messaging elements"
        - "Identify SEO-friendly brand language patterns"
        - "Develop consistent voice guidelines"
      backstory: 
      You are a seasoned Branding and SEO expert with extensive experience in digital marketing, content strategy, and audience engagement. Your ability to analyze tone, sentiment, and 
      keyword optimization makes you the go-to expert for shaping a brand’s voice. With a keen eye for detail, you ensure that every piece of content aligns with the brand’s personality and search engine best practices.
      tools:
        - "content_analysis"
        - "sentiment_analysis"
        - "seo_tools"
      allow_delegation: true
      verbose: true

      prompt:
        system: |
          As a Brand Voice Analyst, analyze the brand's communication style, tone, 
          and messaging patterns while considering SEO optimization opportunities.
          Focus on maintaining authenticity while enhancing search visibility.
        
        task: |
          1. Analyze existing brand communications
          2. Identify core tone and style elements
          3. Evaluate current SEO performance of brand messaging
          4. Develop guidelines for SEO-optimized brand voice
          5. Suggest improvements for visibility while maintaining brand integrity

      expected_output: |
          JSON object structured as follows:
          ```json
          {
            "brand_tone": "Concise description of the brand's tone",
            "key_messaging": [
              "List of core messaging points"
            ],
            "style_guidelines": {
              "writing_style": "Formal/Informal/Conversational",
              "preferred_vocabulary": ["word1", "word2"]
            },
            "seo_recommendations": {
              "keywords": ["keyword1", "keyword2"],
              "meta_description": "Suggested meta description following SEO guidelines"
            }
          }
          ```

# Research: Product Specifics → Understand key product attributes & features
 research_product_specifics:
  id: "task_002"
  name: "Product Specifics Analysis"
  description: |
    Conduct detailed analysis of product attributes, features, and market positioning
      with focus on SEO optimization opportunities.

  agent:
      role: "Product Research Specialist"
      goals:
        - "Analyze product features and specifications"
        - "Identify competitive advantages"
        - "Determine SEO-optimization opportunities"
      backstory: "Experienced product analyst with expertise in SEO optimization"
      tools:
        - "product_analysis"
        - "competitor_research"
        - "market_analysis" 

  expected_output: |
    JSON object structured as follows:
    
    ```json
    {
      "product_name": "Example Product",
      "category": "Example Category",
      "attributes": {
        "feature_1": "Detailed description of feature 1",
        "feature_2": "Detailed description of feature 2"
      },
      "competitive_analysis": {
        "advantage": "Key advantage over competitors",
        "weakness": "Possible weakness compared to competitors"
      },
      "market_positioning": "Brief summary of how the product is positioned in the market."
    }
    ```

  notes: |
    - Ensure that all attributes and competitive analysis are backed by reliable sources.
    - Provide citations or reference points where applicable.
    - The JSON output should be structured and formatted properly.

# Research: Keyword Research → Identify high-impact keywords for visibility
keyword_research:
  id: "task_003"
  name: "Rich Semantic Keyword Analysis"
  
  description: |
    Perform comprehensive semantic keyword research to identify contextually 
      relevant terms and optimize content visibility.

  agent:
      role: "Semantic SEO Specialist"
      goals:
        - "Identify high-value semantic keyword clusters"
        - "Analyze search intent patterns"
        - "Develop comprehensive keyword strategy"
      backstory: "Expert in semantic SEO with focus on AI-driven keyword research"
      tools:
        - "semantic_analysis"
        - "keyword_research"
        - "intent_analysis"

    prompt:
      system: |
        As a Semantic SEO Specialist, analyze and identify semantically related 
        keywords that enhance content visibility while maintaining contextual relevance.
      
      task: |
        1. Analyze existing keyword performance
        2. Identify semantic keyword clusters
        3. Evaluate search intent patterns
        4. Develop recommendations for keyword optimization
        5. Prioritize keywords based on potential impact

  expected_output: |
    JSON object structured as follows:
    
    ```json
    {
      "product_or_topic": "Example Product or Topic",
      "target_audience": "Example Target Audience",
      "high_value_ke

# Research: Rich Semantic Keyword  -> Identify contextually relevant and SEO-rich keywords, including primary, long-tail, and LSI terms, to enhance product visibility. Analyze search intent, competitor keywords, and AI-driven insights to create a diverse, high-impact keyword set for optimization.
research_rich_semantic_keywords:
  id: "task_003"
  name: "Rich Semantic Keyword Analysis"
  description: |
    After analyzing all key exact-match keywords, identify closely semantically related keywords 
    that do not contain the same words but share the same meaning.

    Your analysis should include:
      - **Thematic Groups**: Categorized clusters of semantically related keywords.
      - **Individual Keywords**: High-value keywords not in the same exact match set.
    
    Additionally, classify keywords into:
      - **Close and loose competing keywords**: Keywords that rank for similar intent but vary in phrasing.
      - **Complementary/adjacent keywords**: Keywords that support or enhance the topic coverage.
      - **Substitute keywords**: Alternative keywords that could replace or outperform existing ones.

    Finally, recommend additional keywords that should be prioritized.
  
      agent:
      role: "Semantic SEO Specialist"
      goals:
        - "Identify high-value semantic keyword clusters"
        - "Analyze search intent patterns"
        - "Develop comprehensive keyword strategy"
      backstory: "Expert in semantic SEO with focus on AI-driven keyword research"
      tools:
        - "semantic_analysis"
        - "keyword_research"
        - "intent_analysis"

    prompt:
      system: |
        As a Semantic SEO Specialist, analyze and identify semantically related 
        keywords that enhance content visibility while maintaining contextual relevance.
      
      task: |
        1. Analyze existing keyword performance
        2. Identify semantic keyword clusters
        3. Evaluate search intent patterns
        4. Develop recommendations for keyword optimization
        5. Prioritize keywords based on potential impact
    
    
  agent:
      role: "Semantic SEO Specialist"
      goals:
        - "Identify high-value semantic keyword clusters"
        - "Analyze search intent patterns"
        - "Develop comprehensive keyword strategy"
      backstory: "Expert in semantic SEO with focus on AI-driven keyword research"
      tools:
          - "semantic_analysis"
          - "keyword_research"
          - "intent_analysis"

          
    prompt:
        system: |
          As a Semantic SEO Specialist, analyze and identify semantically related 
          keywords that enhance content visibility while maintaining contextual relevance.
        
  
  expected_output: |
    JSON object structured as follows:
    ```json
    {
      "thematic_groups": [
        {
          "group_name": "AI Technology",
          "keywords": ["machine learning models", "neural networks", "deep learning"]
        }
      ],
      "individual_keywords": ["automated AI research", "AI-driven content strategy"],
      "competing_keywords": {
        "close_match": ["AI research tools", "AI content analysis"],
        "loose_match": ["digital marketing automation", "SEO optimization AI"]
      },
      "complementary_keywords": ["AI content generator", "data-driven marketing"],
      "substitute_keywords": ["AI blog assistant", "semantic keyword research tool"],
      "recommended_keywords": ["future AI trends", "predictive analytics AI"]
    }
    ```

# Research: Competitor Analysis → Analyze top-ranking competitors for insights
research_competitor_analysis:
  description: |
    Conduct in-depth competitor analysis using AI-powered research agents.
    This includes identifying competitors, analyzing their product attributes, SEO strategies, and market positioning.
    The research will highlight key competitive advantages and opportunities.

  input_parameters:
    target_market:
      type: string
      description: "The market or industry to analyze (e.g., SaaS, eCommerce, Automotive)."
    product_name:
      type: string
      description: "The name of the product being analyzed."
    competitors:
      type: list
      description: "A list of competitor names or brands for comparison."
    analysis_type:
      type: list
      description: "Specify the focus of the competitor analysis."
      options: ["SEO", "Product Features", "Pricing", "Marketing Strategy", "Customer Sentiment"]

  expected_output: |
    JSON object structured as follows:
    
    ```json
    {
      "product_name": "Example Product",
      "target_market": "Example Industry",
      "competitor_analysis": [
        {
          "competitor": "Competitor A",
          "market_positioning": "Leader in budget-friendly options",
          "product_features": {
            "feature_1": "Description of feature 1",
            "feature_2": "Description of feature 2"
          },
          "pricing": {
            "base_price": 49.99,
            "subscription_options": ["Monthly", "Yearly"]
          },
          "SEO_strategy": {
            "top_keywords": ["keyword1", "keyword2"],
            "organic_traffic": 500000,
            "backlink_count": 1200
          },
          "marketing_strategy": {
            "channels": ["Social Media", "Email Marketing"],
            "campaign_success": "High engagement on Instagram and YouTube"
          },
          "customer_sentiment": {
            "positive_reviews": 85,
            "negative_reviews": 15,
            "common_complaints": ["Limited customization", "High learning curve"]
          }
        }
      ]
    }
    ```

  notes: |
    - Competitor analysis should be based on reliable data sources such as web scraping, SEO tools, and customer reviews.
    - The JSON output should be structured and formatted properly.
    - If multiple competitors are analyzed, ensure a comparative analysis is presented.

# Research: Trends → Discover emerging trends in the product category
research_trends:
  description: |
    Conduct trend analysis to identify emerging market patterns, consumer behavior shifts, 
    and industry innovations. This research helps businesses stay ahead of competitors 
    and adapt their strategies effectively.

  input_parameters:
    industry:
      type: string
      description: "The specific industry or market to analyze (e.g., technology, fashion, healthcare)."
    timeframe:
      type: string
      description: "The period for trend analysis (e.g., last 6 months, past year, upcoming trends)."
    data_sources:
      type: list
      description: "Sources for data collection (e.g., Google Trends, social media, industry reports)."
      options: ["Google Trends", "Social Media", "News Articles", "Industry Reports", "Competitor Analysis"]
    geographic_focus:
      type: string
      description: "Specify a region or global scope for trend research."

  expected_output: |
    JSON object structured as follows:

    ```json
    {
      "industry": "Technology",
      "timeframe": "Past 6 Months",
      "trends": [
        {
          "trend_name": "AI in Marketing",
          "popularity_growth": "75%",
          "key_drivers": [
            "Increased AI adoption in automation",
            "Rising interest in personalized marketing"
          ],
          "impact_on_market": "High",
          "supporting_sources": [
            {
              "source_name": "Google Trends",
              "link": "https://trends.google.com/example"
            },
            {
              "source_name": "Industry Report",
              "link": "https://example.com/ai-marketing-report"
            }
          ]
        },
        {
          "trend_name": "Sustainable Tech",
          "popularity_growth": "60%",
          "key_drivers": [
            "Consumer demand for eco-friendly products",
            "Regulatory changes promoting sustainability"
          ],
          "impact_on_market": "Medium",
          "supporting_sources": [
            {
              "source_name": "Social Media",
              "link": "https://twitter.com/trending_topic"
            }
          ]
        }
      ]
    }
    ```

  notes: |
    - Ensure all trends are backed by credible data sources.
    - Each trend should have at least two supporting sources.
    - Analysis should include potential business impact and future predictions.

# Research: Voice of Customer → Extract customer feedback & sentiment for improvements
voice_of_customer_researcher:
  role: >
    Voice of Customer (VoC) Researcher
  goal: >
    Extract, analyze, and interpret customer feedback to improve brand messaging, 
    customer experience, and overall brand perception. Utilize sentiment analysis 
    and customer insights to identify trends, strengths, and areas for improvement.
  backstory: >
    You are a consumer psychology and market research expert, specializing in 
    analyzing customer sentiment across various platforms, including surveys, 
    reviews, and social media. Your deep understanding of audience perception 
    allows you to pinpoint what resonates with customers and what needs refinement.  
    Your insights drive strategic improvements in brand communication and customer engagement.
  tools:
    - SentimentAnalysisTool
    - SurveyAnalysisTool
    - CustomerReviewScraperTool
    - SocialListeningTool
  allow_delegation: true
  verbose: true

# Research: Category-Specific Nuances → Understand SEO rules for the product category
category_seo_researcher:
  role: >
    Category-Specific SEO Researcher
  goal: >
    Research and analyze SEO best practices tailored to the specific product category. 
    Ensure all content follows industry-specific ranking rules and search engine guidelines 
    to improve visibility, discoverability, and engagement.
  backstory: >
    You are a highly skilled SEO strategist with expertise in industry-specific 
    search engine ranking factors. Your experience includes technical SEO, 
    keyword optimization, and competitive analysis. You understand how different 
    product categories require unique SEO strategies to maximize their search performance.  
    Your insights help shape data-driven content that aligns with Google’s latest 
    algorithms and industry trends.
  tools:
    - SEOKeywordResearchTool
    - CompetitorSEOAnalysisTool
    - SERPMonitoringTool
    - SchemaMarkupValidatorTool
  allow_delegation: true
  verbose: true

# Research: Assessment of Current Listing → Audit existing content for gaps & weaknesses
# Research: Platform Policies → Ensure compliance with Amazon SEO & listing guidelines

# 2. Content Strategy & Planning Phase
# Goal: Define a structured plan for SEO-optimized content creation.
# Generate: Plan of Action → Outline the SEO strategy based on research findings

# 3. Content Creation & Optimization Phase
# Goal: Generate high-quality, SEO-optimized content based on research insights.
# Generate: Optimized Product Title → Craft an attention-grabbing, keyword-rich product title
# Generate: Key Product Features → Highlight product benefits in an SEO-friendly format
# Generate: Product Description → Create a compelling, SEO-optimized product description
# Generate: Generic Search Keywords → Find additional relevant search terms
# Generate: Image Messaging Outline → Define how images communicate product benefits
# Generate: A+ Content Blocks Outline → Plan enhanced Amazon A+ marketing content

# 4. Quality Assurance & Compliance Phase
# Goal: Validate that the content meets best practices and policy guidelines.
# QA: Best Practices → Ensure the content follows SEO & Amazon listing best practices
# QA: Amazon Policy Compliance (RAG) → Check content for compliance with Amazon’s guidelines

# 5. Export & Deployment Phase
# Goal: Store, distribute, and share optimized content efficiently.
# Export: Save in Mongo → Store the final content in a database
# Export: Create Office Document → Generate a downloadable version for stakeholders
# Export: Send to Notification Service → Notify relevant teams about the new content
